In [11]:
import pandas as pd

train = pd.read_csv("raw_train.csv")
train

          id class                      reactants>reagents>production
0      26182   UNK  CON(C)[C:2](=[O:3])[CH:4]1[CH2:5][CH2:6][N:7](...
1      86857   UNK  CC(C)(C)OC(=O)[NH:21][C@H:20]1[CH2:19][CH2:18]...
2      76265   UNK  Cl[S:5](=[O:6])(=[O:7])[CH:8]=[CH:9][c:10]1[cH...
3      52534   UNK  CC(C)=[C:2]1[CH:3]2[CH2:4][CH2:5][CH:6]1[c:7]1...
4      58325   UNK  [CH3:1][C@H:5]([NH2:6])[C:7](=[O:8])[OH:9]>>[C...
...      ...   ...                                                ...
73188   6441   UNK  [CH3:1][O:2][CH2:3][O:4][c:5]1[c:6]([Cl:7])[cH...
73189  56565   UNK  S=[C:21]1[C:19]([CH3:20])=[N:18][C:17]2([C:6]3...
73190  79172   UNK  C[O:12][C:10]([c:9]1[c:7]([F:8])[cH:6][cH:5][c...
73191    885   UNK  Cl[S:11]([c:10]1[c:2]([CH3:1])[cH:3][cH:4][c:5...
73192  16259   UNK  O[C:14](=[O:15])[C@@H:16]1[CH2:17][C@H:18]1[c:...

[73193 rows x 3 columns]

In [12]:
val = pd.read_csv("raw_val.csv")
val

         id class                      reactants>reagents>production
0       382   UNK  Br[Mg][CH2:2][CH3:1].[C:3](#[N:4])[c:5]1[cH:6]...
1     61024   UNK  O[C:24](=[O:25])[CH2:26][c:27]1[cH:28][cH:29][...
2     49899   UNK  CC(C)(COP(=O)(O)OP(=O)(O)OC[C@H]1O[C@@H](n2cnc...
3     85375   UNK  [CH3:1][C@H:2]([CH2:3][CH2:4][C:5](=[O:6])[OH:...
4     56637   UNK  O=[C:5]([NH:4][CH2:3][CH:2]([CH3:1])[CH2:11][O...
...     ...   ...                                                ...
3655  13457   UNK  Cl[c:9]1[n:10][c:11]([NH:12][c:13]2[cH:14][c:1...
3656  89828   UNK  *[C:4]([CH2:3][CH2:2][CH3:1])=[O:5].Nc1ncnc2c1...
3657  55267   UNK  O=[C:1](Cl)[C:2](=O)Cl.[CH2:3]([OH:4])[CH2:5][...
3658  70788   UNK  [CH3:1][CH2:2][CH2:3][CH2:4][CH2:5]/[CH:6]=[CH...
3659  58375   UNK  CO[CH:9](OC)[CH2:8][NH:7][C:5]([C@@H:4]([CH:2]...

[3660 rows x 3 columns]

In [13]:
test = pd.read_csv("raw_test.csv")
test

          id class                      reactants>reagents>production
0      49868   UNK  [CH3:1][CH2:2][CH2:3][CH2:4][CH2:5][c:6]1[cH:7...
1        146   UNK  O[C:17]([c:16]1[c:2]([CH3:1])[n:3][c:4]([N:5]2...
2      56977   UNK  Cl[CH2:9][c:10]1[cH:11][cH:12][cH:13][cH:14][c...
3      88887   UNK  [CH3:1][CH2:2]/[CH:3]=[CH:4]/[CH2:5]/[CH:6]=[C...
4      80567   UNK  CC[O:15][C:13]([CH:12]([CH2:11][c:10]1[cH:9][c...
...      ...   ...                                                ...
14634   8532   UNK  N[C@@H](CSCS[CH2:1][C@H:2]([NH2:3])[C:4](=[O:5...
14635  40481   UNK  C1C[CH2:26][CH2:25]O1.O[CH2:20][CH:21]1[CH2:22...
14636  46216   UNK  Br[CH2:4][C:5](=[O:6])[c:7]1[cH:8][cH:9][c:10]...
14637   7098   UNK  CCCCCCCC/C=C\CCCCCCCC(=O)O[CH:10]([CH2:9][CH2:...
14638  67497   UNK  CC(C)N(C(C)C)[P:21]([O:23][C:24]([CH3:25])([CH...

[14639 rows x 3 columns]

In [10]:
# get the number of same reactions in train and val
train_reactions = set(train["reactants>reagents>production"])
val_reactions = set(val["reactants>reagents>production"])
same_reactions = train_reactions.intersection(val_reactions)
same_reactions

set()

In [6]:
import pandas as pd

dataset = pd.read_csv("BioChem+PlantCyc.csv")
dataset

              id     class                      reactants>reagents>production
0              0       UNK  O[C:19]([c:18]1[c:2]([CH3:1])[nH:3][c:4](/[CH:...
1              1       UNK  [CH3:1][N+:7]([CH3:5])([CH2:6][CH2:2][OH:3])[C...
2              2       UNK  CCCCCCCCCCCC(=O)[O:8][c:7]1[cH:6][cH:5][c:4]([...
3              3       UNK  O[C:10]([c:9]1[cH:8][c:7]2[cH:6][cH:5][cH:4][c...
4              4       UNK  O[CH:14]1[CH2:13][CH2:12][N:11]([C:2](=[O:1])[...
...          ...       ...                                                ...
91567  RXN-16119  PWY-6453  [CH3:67][C:68]([CH3:69])([C@@H:70]([OH:71])[C:...
91568   RXN-8722  PWY-5478  [CH2:1]([O:2][C:3]([C:4]1=[CH:10][C:9]([OH:11]...
91569   RXN-7853  PWY-5140  [CH3:1][CH2:2][CH2:3][CH2:4][CH2:5][C:6]1=[CH:...
91570  RXN-20408  PWY-8043  [CH3:2][CH2:3][C@H:4]([NH3+:8])[C:5](=[O:6])[O...
91571  RXN-18163       UNK  [CH3:1][S:2][CH2:3][CH2:4][CH2:5][CH2:6][CH2:7...

[91572 rows x 3 columns]

In [7]:
dataset.drop_duplicates(subset=["reactants>reagents>production"], inplace=True)
dataset.reset_index(drop=True, inplace=True)
dataset.to_csv("BioChem+PlantCyc_cleaned.csv", index=False)